#ifndef TICTACTOE_GAMEEVENTTYPE_H
#define TICTACTOE_GAMEEVENTTYPE_H

enum class GameEventType {
    MOVE_PLAYER_PLACEHOLDER, WRITE_PLAYER_SYMBOL, WRITE_MATRIX, WAIT_PLAYER_INPUT, SHUTDOWN
};

#endif //TICTACTOE_GAMEEVENTTYPE_H
